### ISSUE TITLE
Ability to define maximal size of the cache

### ISSUE THREAD

**Issue by paluh** [LuudJanssen/localforage-cache#2]
Thanks a lot for building this lib.

I think that the ability to define max size of the cache could be really useful. I'm not sure how feasible is to handle this limit in bytes but even element number limit could be useful.

Could you please tell me what do you think about such addition?

**Comment by LuudJanssen** [comment]
Hi @paluh, sorry for the late reply! I'm not really maintaining this library, so I'm archiving it. This is basically just a small wrapper around `localforage`, an already existing library. I'm not planning on adding features on top of `localforage`. If you really want this you should open an issue there.
