### ISSUE TITLE
Force cleanup action

### ISSUE THREAD

**Issue by paluh** [LuudJanssen/localforage-cache#3]
It seems that the current API doesn't provide a way to force a cache cleanup - removal of expired items. From my perspective it is a crucial feature for a cache control. Would be so kind and tell me what do you think about it?

**Comment by f3yisayo** [comment]
You can't do this with LocalForage or any wrapper at all, cause browser storage API's don't provide access to what's stored without access to the DOM.

**Comment by LuudJanssen** [comment]
Hi @paluh, sorry for the late reply! I'm not actively maintaining this, so I'm archiving it.

I think in hindsight it would have been a helpful feature to remove all expired items in one method you could run periodically, hope you have found something that fitted your use case.
